name: Update README Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version to update in README'
        required: true
        type: string
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  update-readme:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=LATEST_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Update README with new version
        run: |
          # Only update the plugin application version, not the project version in unipub block
          sed -i "s/\(id(\"dev\.mtctx\.unipub\") version \)\"[^\"]*\"/\1\"${{ steps.version.outputs.VERSION }}\"/g" README.md
          sed -i "s/\(version: \"\)[^\"]*\"/\1${{ steps.version.outputs.VERSION }}\"/g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update README version to ${{ steps.version.outputs.VERSION }}"
            git push
          fi